
stages:
  - node-build
  - android-build
  - ios-build

jobs:
  include:
    - stage: node-build
      language: node_js
      node_js:
        - "8"
      script: 
      - echo 'building node...'
      - echo $TRAVIS_OS_NAME     
    - stage: android-build
      language: android
      android:
        components:
        - tools
        - platform-tools
        - tools
        - build-tools-27.0.2
        - android-27
        - extra
      script: 
      - echo 'building node...'
      - echo $TRAVIS_OS_NAME         
    - stage: ios-build
      language: objective-c
      osx_image: xcode8.3
      script: 
      - echo 'building node...'
      - echo $TRAVIS_OS_NAME  
