
stages:
  - NODE
  - ANDROID
  - IOS

jobs:
  include:
    - stage: NODE
      language: node_js
      node_js:
        - "8"
      services:
        - docker
      script: 
      - echo $TRAVIS_OS_NAME
      - node --version
      
    - stage: ANDROID
      language: android
      android:
        components:
        - tools
        - platform-tools
        - tools
        - build-tools-27.0.2
        - android-27
        - extra
      before_install:
        - nvm install 8
        - yes | sdkmanager "platforms;android-27"
      install:
       - npm install -g cordova
       - gem install fastlane
      script: 
        - echo $TRAVIS_OS_NAME
        - cordova --version
      
    - stage: IOS
      language: objective-c
      osx_image: xcode8.3
      before_install:
        - nvm install 8
      install:
       - npm install -g cordova
       - gem install fastlane
      script: 
      - echo $TRAVIS_OS_NAME
      - cordova --version

