
os: 
  - linux
  - osx
  
stages:
  - node-build
  - cordova-build

stage: node-build
script: echo $TRAVIS_OS_NAME

jobs:
  include:
    - stage: cordova-build
      script: 
      - echo 'building node...'
      - echo $TRAVIS_OS_NAME     
