language: node_js
node_js:
  - "8"
script:
  - echo 'script global'
after_script:
  - echo $FOO
matrix:
  include:
    - script:
        - echo 'script matrix 1'
      env:
        - FOO=foo
    - script:
        - echo 'script matrix 2'
      env:
        - FOO=bar
