os: 
 - linux
 - osx

stages:
  - node-build
  - cordova-build
  - deploy

script echo $TRAVIS_OS_NAME

jobs:
  include:
    - stage: node-build
      script: echo 'building node...'
    - stage: deploy
      script: echo 'deploying...'
      
