matrix:
  include:
   - os: linux
     language: node_js
   - os: osx
     language: node_js

jobs:
  include:
    - stage: Build
      script: echo $TRAVIS_OS_NAME
    - stage: Deploy
      script: echo $TRAVIS_OS_NAME
