os:
 - linux
 - osx

jobs:
  include:
    - stage: Build
      script: echo $TRAVIS_OS_NAME
      script: echo 'building...'
    - stage: Deploy
      script: echo $TRAVIS_OS_NAME
      script: echo 'deploying...'
      

