matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      script:
        - echo 'hello linux'
    - os: osx
      osx_image: xcode7.2 
      script: 
        - echo 'hello ios'
    
