language: node_js
node_js:
  - "8"
matrix:
  include:
    - script:
      - echo 'script matrix 1'
     - after_script:
      - echo 'after script matrix 1'
    - script:
      - echo 'script matrix 2'
    - after_script:
      - echo 'after script matrix 2'
script:
  - echo 'script global'
after_script:
  - echo 'After script global'
  
