matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      script:
        - echo 'linux'
    - os: osx
      osx_image: xcode7.2 
      script: 
        - echo 'hello ios'

jobs:
  include:
    - stage: Build
      script: echo 'building...'
    - stage: Deploy
      script: echo 'deploying..'
      

